# Generated by Django 4.1 on 2022-10-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='first_name',
        ),
    ]
