# Generated by Django 4.1 on 2022-10-23 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OTHERS', 'Others')], default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
    ]
