# Generated by Django 4.1 on 2022-10-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_subscribe_alter_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='TESTING'),
        ),
    ]
