# Generated by Django 4.1 on 2022-10-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
