# Generated by Django 4.1 on 2022-10-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_rename_first_name_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id']},
        ),
    ]
